/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doctorbooking;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author amalp
 */

public class mainapp extends javax.swing.JFrame {
 
    /**
     * Creates new form server
     */
    public mainapp() {
        
        initComponents();
       
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sevl1 = new javax.swing.JLabel();
        sevl2 = new javax.swing.JLabel();
        sevl3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sevt1 = new javax.swing.JTextField();
        sevt2 = new javax.swing.JTextField();
        sevt3 = new javax.swing.JTextField();
        sevt4 = new javax.swing.JTextField();
        sevt5 = new javax.swing.JTextField();
        sevt6 = new javax.swing.JTextField();
        sevt7 = new javax.swing.JTextField();
        sevt8 = new javax.swing.JTextField();
        sevt9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));

        sevl1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sevl1.setForeground(new java.awt.Color(51, 0, 51));
        sevl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sevl1.setText("HSM HOSPITAL");

        sevl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevl2.setForeground(new java.awt.Color(0, 102, 102));
        sevl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sevl2.setText("Doctor Name");

        sevl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevl3.setForeground(new java.awt.Color(0, 102, 102));
        sevl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sevl3.setText("Speciality");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("No.Patient");

        sevt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevt1.setForeground(new java.awt.Color(0, 102, 102));
        sevt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sevt2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevt2.setForeground(new java.awt.Color(0, 102, 102));
        sevt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sevt3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevt3.setForeground(new java.awt.Color(0, 102, 102));
        sevt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sevt4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevt4.setForeground(new java.awt.Color(0, 102, 102));
        sevt4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sevt5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sevt6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevt6.setForeground(new java.awt.Color(0, 102, 102));
        sevt6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sevt7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevt7.setForeground(new java.awt.Color(0, 102, 102));
        sevt7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sevt8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevt8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        sevt9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevt9.setForeground(new java.awt.Color(0, 102, 102));
        sevt9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sevl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sevt7)
                    .addComponent(sevt4)
                    .addComponent(sevt1)
                    .addComponent(sevl2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sevl3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(sevt2)
                    .addComponent(sevt5)
                    .addComponent(sevt8))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(sevt3)
                    .addComponent(sevt6)
                    .addComponent(sevt9))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sevl1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sevl2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sevl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sevt1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(sevt2)
                    .addComponent(sevt3))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sevt4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(sevt5)
                    .addComponent(sevt6))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sevt7, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(sevt8)
                    .addComponent(sevt9))
                .addGap(129, 129, 129))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
     public void Conn()throws Exception
    {
        Class.forName("com.mysql.cj.jdbc.Driver");    
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/appointment","root","root123") ;
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select d_name,speciality from doctor;");
            for(int i=0;rs.next();i++)
            {
                sevt1.setText(rs.getString(1));
                sevt2.setText(rs.getString(2));
              //  System.out.print(rs.getString(3));
             //  sevt3.setText(rs.getString(3));
               
            }     
        
    }
        catch(Exception e)
        {
            System.out.println(e);
        }
}

    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
              server sr = new server();
              sr.setVisible(true);
                try {
                    sr.Conn();
                } catch (Exception ex) {
                    Logger.getLogger(server.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sevl1;
    private javax.swing.JLabel sevl2;
    private javax.swing.JLabel sevl3;
    private javax.swing.JTextField sevt1;
    private javax.swing.JTextField sevt2;
    private javax.swing.JTextField sevt3;
    private javax.swing.JTextField sevt4;
    private javax.swing.JTextField sevt5;
    private javax.swing.JTextField sevt6;
    private javax.swing.JTextField sevt7;
    private javax.swing.JTextField sevt8;
    private javax.swing.JTextField sevt9;
    // End of variables declaration                   
}

